export const GET_USER_CONTENT_REQUEST = "GET_USER_CONTENT_REQUEST";
export const GET_USER_CONTENT_SUCCESS = "GET_USER_CONTENT_SUCCESS";
export const GET_USER_CONTENT_FAILURE = "GET_USER_CONTENT_FAILURE";

export const ADD_USER_CONTENT_REQUEST = "ADD_USER_CONTENT_REQUEST";
export const ADD_USER_CONTENT_SUCCESS = "ADD_USER_CONTENT_SUCCESS";
export const ADD_USER_CONTENT_FAILURE = "ADD_USER_CONTENT_FAILURE";
